project_id = "hlkzgmppfowvkoppqckk"

[functions.ai-chat]
verify_jwt = false

[functions.rag-retrieval]
verify_jwt = false

[functions.populate-rag]
verify_jwt = false

[functions.save-lead]
verify_jwt = false

[functions.get-leads]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.tts]
verify_jwt = false
